server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/expensedb
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: uPXZL9F+KlcBvNMsPb/YX2szWTz7+s0LB8lD69ybZOA=
  expiration: 3600000 
